# Generated by Django 5.1 on 2024-10-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_animal_fosterer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='adoption_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Fostered', 'Fostered')], default='Available', max_length=20),
        ),
    ]
