# Generated by Django 5.1 on 2024-09-07 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0002_update'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprite_sheet', models.CharField(choices=[('husky/one.png', 'Husky Style 1'), ('husky/two.png', 'Husky Style 2'), ('husky/three.png', 'Husky Style 3')], default='husky/one.png', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
