# Generated by Django 5.1 on 2024-09-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sprite_breed_alter_sprite_sprite_sheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprite',
            old_name='sprite_sheet',
            new_name='url',
        ),
        migrations.AddField(
            model_name='sprite',
            name='colour',
            field=models.CharField(choices=[('one', 'Colour 1'), ('two', 'Colour 2'), ('three', 'Colour 3')], default='one', max_length=50),
        ),
    ]
