# Generated by Django 5.1 on 2024-09-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_sprite_sheet_sprite_url_sprite_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprite',
            name='last_checked',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sprite',
            name='satiation',
            field=models.IntegerField(default=50),
        ),
    ]
