# Generated by Django 5.1 on 2024-09-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_sprite_last_checked_sprite_satiation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprite',
            name='current_state',
            field=models.CharField(choices=[('standing', 'Standing'), ('running', 'Running')], default='standing', max_length=10),
        ),
    ]
